//! Remaining S3 MAC initialization helpers, reviewed against the linked blob.
//!
//! These are register defaults, not PHY calibration or a Bluetooth coexistence
//! implementation. See `docs/esp32s3/MAC-HELPERS.md` for the instruction evidence.
//! All entry points require exclusive MAC ownership during initialization.

#[inline(always)]
fn read(address: usize) -> u32 {
    #[cfg(test)]
    return tests::read(address);
    #[cfg(not(test))]
    unsafe {
        (address as *const u32).read_volatile()
    }
}

#[inline(always)]
fn write(address: usize, value: u32) {
    #[cfg(test)]
    tests::write(address, value);
    #[cfg(not(test))]
    unsafe {
        (address as *mut u32).write_volatile(value);
    }
}

#[inline(always)]
fn update(address: usize, keep: u32, set: u32) {
    write(address, (read(address) & keep) | set);
}

pub(crate) unsafe fn hal_crypto_init() {
    write(0x60033800, 0x30000);
    write(0x60033804, 0x30000);
    write(0x60033808, 0);
    write(0x6003380c, 0);
    write(0x60033810, 0);
    update(0x60033840, u32::MAX, 0x19);
}

pub(crate) unsafe fn hal_attenna_init() {
    // The original spelling is retained for comparison with the blob symbol.
    // Clear the antenna selection across all eight slots before changing mode.
    for slot in 0..8 {
        update(0x60034314 - slot * 0x4c, !7, 0);
    }
    for slot in 0..8 {
        let address = 0x60034314 - slot * 0x4c;
        // Keep these three transactions separate, including their intervening reads.
        update(address, !8, 0);
        update(address, u32::MAX, 0x20);
        update(address, !0x10, 0);
    }
    update(0x600332a8, !7, 0);
    update(0x600332a8, u32::MAX, 0x20);
}

pub(crate) unsafe fn hal_mac_rate_autoack_init() {
    write(0x60033418, 0);
    write(0x6003340c, 0x19191919);
}

pub(crate) unsafe fn hal_coex_pti_init() {
    update(0x60035084, u32::MAX, 2);
}

pub(crate) unsafe fn hal_set_rx_active_pti(priority: u32) {
    update(0x600332ac, !0xf, priority & 0xf);
}

pub(crate) unsafe fn hal_set_rx_ack_pti(priority: u32) {
    update(0x600332ac, !0xf0, (priority & 0xf) << 4);
}

pub(crate) unsafe fn hal_set_wifi_default_pti(priority: u32) {
    update(0x60035094, !0xf00, (priority & 0xf) << 8);
}

pub(crate) unsafe fn hal_timer_update_by_rtc(enable: u32, calibration: u32) {
    // The original ABI consumes only the low byte of `enable`.
    if enable as u8 != 0 {
        update(0x60035024, u32::MAX, 1 << 25);
        update(0x60035058, !0x3ffff, calibration & 0x3ffff);
    } else {
        update(0x60035024, !(1 << 25), 0);
    }
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use std::{cell::RefCell, collections::BTreeMap, vec, vec::Vec};

    // Golden traces below are transcribed from the original instructions, not
    // generated by executing another copy of the Rust implementation.
    type Access = (char, usize, u32);
    #[derive(Default)]
    struct State {
        seed: u32,
        registers: BTreeMap<usize, u32>,
        trace: Vec<Access>,
    }
    std::thread_local! {
        static STATE: RefCell<State> = RefCell::new(State::default());
    }
    fn reset(seed: u32) {
        STATE.with(|state| {
            *state.borrow_mut() = State {
                seed,
                ..State::default()
            }
        });
    }
    pub(super) fn read(address: usize) -> u32 {
        assert_eq!(address & 3, 0);
        STATE.with(|state| {
            let mut state = state.borrow_mut();
            let value = *state.registers.get(&address).unwrap_or(&state.seed);
            state.trace.push(('r', address, value));
            value
        })
    }
    pub(super) fn write(address: usize, value: u32) {
        assert_eq!(address & 3, 0);
        STATE.with(|state| {
            let mut state = state.borrow_mut();
            state.registers.insert(address, value);
            state.trace.push(('w', address, value));
        });
    }
    fn check(expected: Vec<Access>) {
        STATE.with(|state| assert_eq!(state.borrow().trace, expected));
    }
    const SEEDS: [u32; 4] = [0, u32::MAX, 0xaaaaaaaa, 0x55555555];

    #[test]
    fn crypto_defaults_preserve_control_bits_and_transaction_order() {
        for seed in SEEDS {
            reset(seed);
            unsafe { hal_crypto_init() };
            check(vec![
                ('w', 0x60033800, 0x30000),
                ('w', 0x60033804, 0x30000),
                ('w', 0x60033808, 0),
                ('w', 0x6003380c, 0),
                ('w', 0x60033810, 0),
                ('r', 0x60033840, seed),
                ('w', 0x60033840, seed | 0x19),
            ]);
        }
    }

    #[test]
    fn antenna_visits_all_eight_slots_in_two_passes_without_combining_writes() {
        let addresses = [
            0x60034314, 0x600342c8, 0x6003427c, 0x60034230, 0x600341e4, 0x60034198, 0x6003414c,
            0x60034100,
        ];
        for seed in SEEDS {
            reset(seed);
            unsafe { hal_attenna_init() };
            let mut expected = Vec::new();
            for address in addresses {
                expected.extend([('r', address, seed), ('w', address, seed & 0xfffffff8)]);
            }
            for address in addresses {
                expected.extend([
                    ('r', address, seed & 0xfffffff8),
                    ('w', address, seed & 0xfffffff0),
                    ('r', address, seed & 0xfffffff0),
                    ('w', address, (seed & 0xfffffff0) | 0x20),
                    ('r', address, (seed & 0xfffffff0) | 0x20),
                    ('w', address, (seed & 0xffffffe0) | 0x20),
                ]);
            }
            expected.extend([
                ('r', 0x600332a8, seed),
                ('w', 0x600332a8, seed & 0xfffffff8),
                ('r', 0x600332a8, seed & 0xfffffff8),
                ('w', 0x600332a8, (seed & 0xfffffff8) | 0x20),
            ]);
            assert_eq!(expected.len(), 68);
            check(expected);
        }
    }

    #[test]
    fn autoack_defaults_use_distinct_registers_in_original_order() {
        reset(u32::MAX);
        unsafe { hal_mac_rate_autoack_init() };
        check(vec![('w', 0x60033418, 0), ('w', 0x6003340c, 0x19191919)]);
    }

    #[test]
    fn coexistence_default_enable_preserves_unrelated_bits() {
        for seed in SEEDS {
            reset(seed);
            unsafe { hal_coex_pti_init() };
            check(vec![('r', 0x60035084, seed), ('w', 0x60035084, seed | 2)]);
        }
    }

    #[test]
    fn priority_fields_mask_inputs_and_preserve_neighboring_fields() {
        for seed in SEEDS {
            for priority in (0..=255).chain([0x12345678, u32::MAX]) {
                for (function, address, mask, shift) in [
                    (
                        hal_set_rx_active_pti as unsafe fn(u32),
                        0x600332ac,
                        0xfffffff0,
                        0,
                    ),
                    (
                        hal_set_rx_ack_pti as unsafe fn(u32),
                        0x600332ac,
                        0xffffff0f,
                        4,
                    ),
                    (
                        hal_set_wifi_default_pti as unsafe fn(u32),
                        0x60035094,
                        0xfffff0ff,
                        8,
                    ),
                ] {
                    reset(seed);
                    unsafe { function(priority) };
                    check(vec![
                        ('r', address, seed),
                        ('w', address, (seed & mask) | ((priority & 15) << shift)),
                    ]);
                }
            }
        }
    }

    #[test]
    fn rtc_timer_masks_calibration_and_obeys_byte_enable_including_disable_branch() {
        for seed in SEEDS {
            for enable in [0, 1, 2, 255, 256, 257, u32::MAX] {
                for calibration in [0, 1, 44462, 0x3ffff, 0x40000, 0x12345678, u32::MAX] {
                    reset(seed);
                    unsafe { hal_timer_update_by_rtc(enable, calibration) };
                    if enable & 255 == 0 {
                        check(vec![
                            ('r', 0x60035024, seed),
                            ('w', 0x60035024, seed & 0xfdffffff),
                        ]);
                    } else {
                        check(vec![
                            ('r', 0x60035024, seed),
                            ('w', 0x60035024, seed | 0x2000000),
                            ('r', 0x60035058, seed),
                            (
                                'w',
                                0x60035058,
                                (seed & 0xfffc0000) | (calibration & 0x3ffff),
                            ),
                        ]);
                    }
                }
            }
        }
    }
}
